tue-robotics/tue_robocup

challenge_gpsr/src/challenge_gpsr/gpsr.py
@egeerts should this be merged?
=> [challenge_gpsr] modified files on athome1

challenge_speech_recognition/src/2_indirect_speech_recognition.py
These files were modified on amigo3. @egeerts should these changes be merged?
=> [speech_recognition] Add modified files on amigo3

robot_skills/src/robot_skills/world_model_ed.py
Fix some issues introduced by the kdl_datatypes
=> Address https://github.com/tue-robotics/tue_robocup/issues/183

challenge_speech_recognition/src/indirect_speech_recognition.py, challenge_spr/src/challenge_spr_states/bluff_game.py, robot_skills/src/robot_skills/world_model_ed.py, robot_skills/test/test_worldmodel.py
Fixes https://github.com/tue-robotics/tue_robocup/issues/234 to make code cleaned and more consistent
=> Fix/234 to make get_closest_entity more consistent with get_entity

robot_smach_states/src/robot_smach_states/util/startup.py
This will allow users to kill challenges, cool huh?
=> Add --debug switch to enable the introspection server

robot_skills/src/robot_skills/util/kdl_conversions.py
instead of waiting for transform at Time.now()
=> fix(kdl_conversions): get latest available transform

tue_robocup/package.xml
This reverts commit e5e9a28d5821265313f85772f70b629c1422dca2.
=> Revert "Update package.xml"

robocup_knowledge/src/robocup_knowledge/environments/robotics_testlabs/common.py
Based on a mapping of rooms to most probable manipulation locations. In the future, this will be replaced by searching for objects at all locations in the given room.
=> fix(robotics_testlabs/common): add room based manipulation location

challenge_help_me_carry/src/challenge_help_me_carry.py
What sort of command should the operator say
Fix for everything in https://github.com/tue-robotics/tue_robocup/issues/270
=> Clear up user interface of help-me-carry

robot_smach_states/src/robot_smach_states/utility.py
This way you can easily use smach_states seperate
Just this file, but should be done in all smach_states
=> use userdata=None for states which don't use userdata

.travis.yml
Should work when https://github.com/tue-robotics/tue-env/pull/98 is fixed.
Last two commits here are tests:
https://travis-ci.org/tue-robotics/tue_robocup/builds
=> Switch to docker CI

challenge_spr/src/challenge_spr_states/riddle_game.py, robot_skills/src/robot_skills/api.py
=> doc(Api) Added docstring to query function

robot_skills/src/robot_skills/api.py
Depends on tue-robotics/dragonfly_speech_recognition#20
=> Add the restart_dragonfly call

robot_skills/src/robot_skills/api.py, robot_smach_states/src/robot_smach_states/utility.py
=> add restart to initialize

challenge_gpsr/src/gpsr.py
=> finished when equal or bigger

challenge_set_a_table/README.md, challenge_set_a_table/src/challenge_set_a_table.py, challenge_set_a_table/src/challenge_set_a_table_states/fetch_command.py
Still work in progress, it will be tested in Sat 8 July 2017.
=> [WIP] Added functionality for fetching commands

challenge_set_a_table/src/challenge_set_a_table.py, robocup_knowledge/src/robocup_knowledge/environments/robotics_testlabs/challenge_set_a_table.py
I did a bad review as well
Fixes some oopsies merged with https://github.com/tue-robotics/tue_robocup/pull/335
=> Add some knowledge for SATTU and fix some transitions.

robot_skills/src/robot_skills/amigo.py, robot_skills/src/robot_skills/robot.py, robot_skills/src/robot_skills/ssl.py
=> refactor(ssl): To different file, doc and to robot.py

challenge_rips/README.md
=> update readme rips

robot_smach_states/src/robot_smach_states/util/robocup_recorder.py, test_tools/data_collection/robocup_recorder.py
Should be merged in combination with tue-robotics/amigo_bringup#69 tue-robotics/robot_launch_files#17
=> feat(robocup_recorder): is now a server that can be triggered to record

challenge_demo/README.md, robocup_knowledge/src/robocup_knowledge/environments/robotics_testlabs/challenge_demo.py
updated ReadMe file, updated knowledge file
=> Demo knowledge patch 1

challenge_demo/src/demo.py, robocup_knowledge/src/robocup_knowledge/environments/robotics_testlabs/challenge_demo.py
=> fix(demo grammar): remove ROOM_OR_LOCATION target

challenge_spr/README.md, challenge_spr/src/challenge_spr.py
Updated README, according to Issue #447 
Updated Challenge file, according to Issue #448
=> Spr readme update

challenge_spr/src/challenge_spr_states/bluff_game.py, challenge_spr/src/challenge_spr_states/riddle_game.py
It was returning: "Whoops! I cannot compare categories!"
Now it successfully compares the categories of 2 objects.
=> Fixed category comparison question and Crash of SPR challenge #478. 

robot_smach_states/src/robot_smach_states/navigation/follow_operator.py
Adds preemption checks in while loops
=> fix(follow_operator): add preempt request checks

robot_skills/src/robot_skills/api.py
plus python3 compatibility issue
=> hmi try/except TimeoutException

robot_skills/src/robot_skills/base.py
Fixed called get_state when no goal is running
=> fix(base): check if goal is running before get_state

robocup_knowledge/src/robocup_knowledge/environments/robotics_testlabs/common.py
Was not in sync with labels of tensorflow model
=> typo in deodorant

challenge_spr/src/challenge_spr_states/detect.py, robot_skills/src/robot_skills/perception.py
Fixes #539
To test:
run SPR ```(amigo-challenge-spr)```
block kinect, so no people are detected.
Challenge shouldn't crash during crowd detection.
Already tested on AMIGO.
=> Fix crash in crowd detection

challenge_gpsr/README.md
I did an update on the README about the challenge flow. It could use some more testing information though. @timassman, could you add instructions on how to install and use the command generator once you have that set up?
=> WIP: doc(gpsr): update readme

challenge_final/src/challenge_final/pointing_detector.py, challenge_help_me_carry/src/challenge_help_me_carry.py, challenge_manipulation/src/empty_shelf_designator.py, challenge_manipulation/src/manipulation.py, challenge_restaurant/src/challenge_restaurant/store_waypoint.py, challenge_restaurant/src/old/automatic_side_detection.py, challenge_restaurant/src/old/challenge_restaurant.py, challenge_storing_groceries/src/challenge_storing_groceries/empty_shelf_designator.py, robot_skills/src/robot_skills/base.py, robot_skills/src/robot_skills/head.py, robot_skills/src/robot_skills/perception.py, robot_skills/src/robot_skills/util/entity.py, robot_skills/src/robot_skills/util/kdl_conversions.py, robot_skills/src/robot_skills/util/nav_analyzer.py, robot_skills/src/robot_skills/util/shape.py, robot_skills/src/robot_skills/world_model_ed.py, robot_skills/test/test_arms.py, robot_smach_states/src/robot_smach_states/manipulation/grab.py, robot_smach_states/src/robot_smach_states/manipulation/grasp_point_determination.py, robot_smach_states/src/robot_smach_states/manipulation/place.py, robot_smach_states/src/robot_smach_states/navigation/follow_operator.py, robot_smach_states/src/robot_smach_states/navigation/navigate_to_symbolic.py, robot_smach_states/src/robot_smach_states/navigation/navigation.py, robot_smach_states/src/robot_smach_states/perception.py, robot_smach_states/src/robot_smach_states/startup.py, robot_smach_states/src/robot_smach_states/util/designators/ed_designators.py, robot_smach_states/src/robot_smach_states/util/geometry_helpers.py
Renaming all kdlCamelCase functions to kdl_camel_case functions
=> 193 fix kdl camel case

robot_smach_states/src/robot_smach_states/navigation/navigate_to_symbolic.py
This simplifies the use of navigating to a room.
=> Add NavigateToRoom

challenge_demo/README.md
Added more details of the commands available for start-up.
=> Updated Start-up commands

robot_skills/src/robot_skills/robot.py, robot_skills/src/robot_skills/sergio.py
Should fix https://github.com/tue-robotics/tue_robocup/issues/581
=> Ignore some robot parts for diagnostics

challenge_demo/src/demo.py
I don't know if the trigger topic was hardcoded ```/amigo/trigger``` for a reason, but this should work the same and should also work with Hero (and Sergio).
=>  Trigger topic now based on robot name and Hero included as robot

robot_smach_states/src/robot_smach_states/util/geometry_helpers.py
Fixes issue #632. Tested on Hero and it works.
=> Changed order of frame multiplication to take orientation into account

challenge_storing_groceries/src/challenge_storing_groceries/config.py, challenge_storing_groceries/src/challenge_storing_groceries/open_door.py, challenge_storing_groceries/src/challenge_storing_groceries/storing_groceries.py
I picked only the commits concerned with door opening from https://github.com/tue-robotics/tue_robocup/pull/641
=> Rwc2018: add only door opening to storing groceries

robocup_knowledge/src/robocup_knowledge/environments/siza_demo/challenge_rips.py, robot_skills/src/robot_skills/hero.py, robot_skills/src/robot_skills/robot.py, robot_smach_states/src/robot_smach_states/human_interaction/human_interaction.py, robot_smach_states/src/robot_smach_states/startup.py
Fixes required for Hero to be able to do the RIPS.
=> Hero fixes based on testing

robot_skills/src/robot_skills/amigo.py, robot_skills/src/robot_skills/base.py, robot_skills/src/robot_skills/ears.py, robot_skills/src/robot_skills/lights.py, robot_skills/src/robot_skills/sergio.py, robot_skills/src/robot_skills/speech.py, robot_skills/src/robot_skills/torso.py, robot_skills/src/robot_skills/world_model_ed.py, robot_skills/test/test_arms.py, robot_skills/test/test_audio.py, robot_skills/test/test_head.py, robot_skills/test/test_person_recognition.py, robot_skills/test/test_speech_recognition.py, robot_skills/test/test_worldmodel.py
=> Robot skills cleanup

challenge_gpsr/src/gpsr.py
Adjust GPSR to match https://github.com/tue-robotics/conversation_engine/pull/23
=> Use unit-testable API of conv. engine

robot_skills/src/robot_skills/hero.py, robot_skills/src/robot_skills/perception.py
This helps solve #712
Ensures hero calls the correct service to project 2d roi's to 3d positions
Fix requires tue-robotics/hero_bringup/#12
=> rgbd_3d_point

challenge_help_me_carry/src/challenge_help_me_carry.py, challenge_help_me_carry/src/challenge_help_me_carry2.py, robot_skills/src/robot_skills/amigo.py, robot_skills/src/robot_skills/hero.py, robot_skills/src/robot_skills/mockbot.py, robot_skills/src/robot_skills/robot.py, robot_skills/src/robot_skills/sergio.py
Use arm name supplied by the robot constructor itself to name an arm.
Addresses #740
=> Add arms of robot itself

challenge_help_me_carry/src/challenge_help_me_carry.py, challenge_help_me_carry/src/challenge_help_me_carry2.py, challenge_manipulation/src/manipulation.py, challenge_set_a_table/src/challenge_set_a_table_states/manipulate_machine.py, challenge_storing_groceries/src/challenge_storing_groceries/manipulate_machine.py, challenge_test/src/test_states.py, robot_skills/src/robot_skills/robot.py, robot_smach_states/src/robot_smach_states/clear.py, robot_smach_states/src/robot_smach_states/console-nl.py, robot_smach_states/src/robot_smach_states/manipulation/place.py, robot_smach_states/src/robot_smach_states/util/designators/arm.py
Reroute Arm*Designator classes to use Robot.get_arm() as well.
=> Arm designators fix

robot_skills/src/robot_skills/arms.py
=> Forward the base_offset value through PublicArm

robot_skills/src/robot_skills/robot.py, robot_skills/src/robot_skills/util/decorators.py
Fix arms keys
Make deprecated decorators more similar
=> Fix deprecated arms

challenge_gpsr/src/gpsr.py, robot_skills/src/robot_skills/amigo.py, robot_skills/src/robot_skills/arms.py, robot_skills/src/robot_skills/hero.py, robot_skills/src/robot_skills/robot.py, robot_skills/src/robot_skills/sergio.py, robot_smach_states/src/robot_smach_states/manipulation/grab.py, robot_smach_states/src/robot_smach_states/manipulation/manipulation.py, robot_smach_states/src/robot_smach_states/manipulation/place.py, robot_smach_states/src/robot_smach_states/navigation/navigate_to_grasp.py, robot_smach_states/src/robot_smach_states/startup.py, robot_smach_states/src/robot_smach_states/util/designators/arm.py
(Also fixes GPSR)
Requires https://github.com/tue-robotics/action_server/pull/112
=> Fix arm shit including some Hacks. But without this PR, robot is useless

robot_smach_states/src/robot_smach_states/util/designators/checks.py
=> Rgo2019 fix check resolve type

challenge_eegpsr/src/eegpsr.py, challenge_eegpsr/src/test_recognition.py, challenge_eegpsr/test/navigate_in_front_of.py, robocup_knowledge/src/robocup_knowledge/environments/rgo2019/challenge_eegpsr.py
Refactored robot constructions and addition of rgo2019 knowledge only. No actual relevant code changes.
Fixes #819
=> Rgo2019 challenge eegpsr

challenge_final/CMakeLists.txt, challenge_final/package.xml, challenge_final/scripts/detect_persons_caller.py, challenge_final/src/challenge_final/open_door.py, challenge_final/src/challenge_final/track_operator.py
- remove unused dependencies, most important head_ref_ed_client
- add missing dependencies
- small code fixes
=> some cleaning up of challenge_final

robot_skills/src/robot_skills/lights.py
Please use this PR instead of #847 as this commit is already on the RGO branches. When merging #847, this will cause merge issues later on.
=> Move RBGLightCommand to tue_msgs

robot_smach_states/src/robot_smach_states/startup.py
=> a slightly hacky fix for StartChallengeRobust

challenge_gpsr/src/gpsr.py
remove this exception in the entire codebase
=> Remove GoalNotSucceededException from codebase (only TimeoutException)

azure-pipelines.yml
As fixed in tue-robotics/tue-env#421
=> fix branch name in azure config

azure-pipelines.yml
Apply https://github.com/tue-robotics/tue-env/pull/431
=> (azure) only run if PACKAGES_DICT != {}

challenge_presentation/src/challenge_presentation/presentation_hero.py
merge after/together with /tue-robotics/hero_description#7
=> Fix(presentation): add goal

robot_smach_states/src/robot_smach_states/world_model.py
The rise state is currently extremely bugged. We need to fix this however for now we should not use the state because it will break existing functionality
=> removed Rise state from inspect

robocup_knowledge/src/robocup_knowledge/environments/robotics_testlabs/challenge_demo.py
Took out unused grammar (not linked to an action server action)
=> remove unused grammar from demo knowledge

robot_smach_states/src/robot_smach_states/util/designators/introspection.py
Fixes https://dev.azure.com/tue-robotics/tue-robotics/_build/results?buildId=1200&view=logs&j=8c5aa4db-64a1-5ba4-017d-d587e9895d06&t=5fb809d6-0a6a-575c-c8da-ff339bedb04c&l=253
Plus some style fixes in separate commit, best to review the commits separate.
=> Fix weakset bug

challenge_dishwasher/src/challenge_dishwasher/open_dishwasher.py, challenge_storing_groceries/src/challenge_storing_groceries/open_door.py
=> Import wrap_angle_pi from util.geometry helpers

challenge_demo/src/demo.py, robot_skills/src/robot_skills/robot.py, robot_smach_states/src/robot_smach_states/reset.py
Add robot function to reset all arms
=> Add robot.reset_all_arms function.

azure-pipelines.yml
Merge with tue-robotics/tue-env#457
=> Fix azure warnings

robot_smach_states/src/robot_smach_states/manipulation/place_designator.py
Should fix https://dev.azure.com/tue-robotics/tue-robotics/_build/results?buildId=1865&view=logs&j=1c73d706-58d9-5536-fd3c-ceb1f182801c&t=ed1e46ef-e08a-5a6a-3531-280bf7da4ce4&l=890
=> Fix check on wrong designator

robot_smach_states/src/robot_smach_states/util/designators/ed_designators.py
@LoyVanBeek although this is pretty old. I still think this one commit should be merged. As right now it doesn't return in that one special case.
=> Locking bug

challenge_demo/src/demo.py
=> (demo) fix smach_states imports

challenge_manipulation/src/empty_shelf_designator.py, challenge_manipulation/src/manipulation.py, challenge_storing_groceries/src/challenge_storing_groceries/empty_shelf_designator.py, challenge_storing_groceries/src/challenge_storing_groceries/inspect_shelves.py, challenge_where_is_this/src/challenge_where_is_this/inform_machine.py, robot_skills/src/robot_skills/mockbot.py, robot_skills/src/robot_skills/world_model_ed.py, robot_smach_states/examples/navigation/example_random_nav2.py, robot_smach_states/src/robot_smach_states/manipulation/grab.py, robot_smach_states/src/robot_smach_states/util/designators/ed_designators.py
Merge after https://github.com/tue-robotics/ed/pull/107
=> Implementing ignore_z of ED simple query

azure-pipelines.yml
Without this condition, azure continues an entire build, even if it is canceled.
=> (azure) add canceled check

robot_skills/src/functionalities/__init__.py, robot_skills/src/functionalities/add_functionalities.py, robot_skills/src/functionalities/arm/guarded_motion.py, robot_skills/src/functionalities/robot_functionality.py, robot_skills/src/robot_skills/hero.py, robot_skills/src/robot_skills/robot.py, robot_skills/src/robot_skills/robot_part.py
Goal of this refactor is to describe a new class of functionalities which can be realised through the use of lower level skills. Currently we only have one of these but in the future we may develop more.
This allows us to specify the requirements of these functionalities in a generic manner and allows these functions to be added to the private interface of the robot automagically.
=> concept illustration

robot_skills/src/robot_skills/arm/arms.py
This legacy thing was left in arms.py. It is no longer used since the gripper has become its own robot part.
=> removed gripper action client from arm interface

challenge_dishwasher/src/challenge_dishwasher/custom_place.py, challenge_dishwasher/src/challenge_dishwasher/open_dishwasher.py, challenge_dishwasher/src/challenge_dishwasher/simple_grab.py, challenge_final/src/challenge_final/navigate_to_and_grab_rack.py, challenge_presentation/src/challenge_presentation/presentation.py, challenge_presentation/src/challenge_presentation/presentation_hero.py, challenge_set_a_table/src/challenge_set_a_table_states/manipulate_machine.py, challenge_set_the_table/src/challenge_set_the_table/navigate_to_and_close_cupboard_drawer.py, challenge_set_the_table/src/challenge_set_the_table/navigate_to_and_open_cupboard_drawer.py, challenge_set_the_table/src/challenge_set_the_table/navigate_to_and_pick_item_from_cupboard_drawer.py, challenge_set_the_table/src/challenge_set_the_table/navigate_to_and_place_item_on_table.py, challenge_storing_groceries/src/challenge_storing_groceries/manipulate_machine.py, challenge_take_out_the_garbage/src/challenge_take_out_the_garbage/drop_down.py, challenge_take_out_the_garbage/src/challenge_take_out_the_garbage/pick_up.py, robot_skills/package.xml, robot_skills/src/robot_skills/mockbot.py, robot_skills/src/robot_skills/util/kdl_conversions.py, robot_smach_states/src/robot_smach_states/manipulation/grab.py, robot_smach_states/src/robot_smach_states/manipulation/manipulation.py, robot_smach_states/src/robot_smach_states/manipulation/place.py, robot_smach_states/test/manipulation/test_manipulation.py
Update robot smach states and challenges to conform to #1058 
Merge after #1058
=> Update robot interface

challenge_manipulation/package.xml, challenge_restaurant/package.xml, challenge_storing_groceries/package.xml
Merge together with https://github.com/tue-robotics/tue-env-targets/pull/212
=> rename python-xhtml2pdf to python-xhtml2pdf-pip

amigo_skills/package.xml, challenge_final/package.xml, challenge_find_my_mates/package.xml, challenge_set_the_table/package.xml, hero_skills/package.xml, robot_skills/README.md, robot_skills/package.xml, robot_skills/src/robot_skills/get_robot.py, robot_skills/test/nosetest/test_get_robot.py, robot_skills/test/rostest/test_compose_robot.py, robot_smach_states/src/robot_smach_states/console.py, sergio_skills/package.xml
=> Register robot

robot_skills/src/robot_skills/torso.py
Should fix #1103
This is >5 year old code 🤣
=> (skills) fix torso limit check

robot_skills/src/robot_skills/arm/arms.py
Try to use the custom message type less
=> cleanup send goal

robot_skills/examples/example_arms.py, robot_skills/src/robot_skills/arm/arms.py
=> fix example arms

azure-pipelines.yml
=> (azure) Fix branch value

robot_skills/src/robot_skills/lights.py
merge together with https://github.com/tue-robotics/tue_msgs/pull/10
=> (skills) RGBLightCommand uses bool instead of std_msgs/bool

robocup_knowledge/src/robocup_knowledge/environments/impuls/challenge_demo.py, robocup_knowledge/src/robocup_knowledge/environments/impuls/challenge_gpsr.py, robocup_knowledge/src/robocup_knowledge/environments/impuls/challenge_restaurant.py, robocup_knowledge/src/robocup_knowledge/environments/impuls/challenge_rips.py, robocup_knowledge/src/robocup_knowledge/environments/impuls/common.py
Files were just copied from robotics_testlab environment
=> add impuls environment

robot_smach_states/examples/example_hear_grasp.py
Should I split changes into multiple PRs?
=> Fix:import module error

robot_skills/src/robot_skills/world_model_ed.py
I feel dirty having touched this...
To be up to date with https://github.com/tue-robotics/rgbd/pull/48
=> update the very very very ugly thing.

challenge_where_is_this/src/challenge_where_is_this/inform_machine.py, challenge_where_is_this/src/challenge_where_is_this/where_is_this.py, robocup_knowledge/src/robocup_knowledge/environments/impuls/challenge_where_is_this.py, robot_smach_states/src/robot_smach_states/human_interaction/give_directions.py, robot_smach_states/src/robot_smach_states/navigation/guidance.py
This PR brings challenge where is this into a working state. i.e. removed bugs. 
We can later see how to optimize performance
=> Fix challenge where is this

challenge_find_my_mates/src/challenge_find_my_mates/locate_people.py, robot_skills/src/robot_skills/world_model_ed.py
Merge after https://github.com/tue-robotics/ed/pull/140 and https://github.com/tue-robotics/ed_gui_server/pull/33
Use rebase
We are merging this one in the `find_my_mates` branch
=> Generate map

robot_skills/src/robot_skills/arm/gripper.py
This was a bug. Previous implementation did not give the intended behaviour
=> check goal not state

robot_smach_states/src/robot_smach_states/manipulation/active_grasp_detector.py
=> Added missing underscore

test_tools/package.xml, test_tools/scripts/record_video_from_camera.py
copied from rwc2022 hero_bringup.
This would be a better place for it.
=> (test_tools) record video from camera

robot_skills/src/robot_skills/arm/arms.py, robot_skills/src/robot_skills/arm/gripper.py, robot_skills/src/robot_skills/arm/handover_detector.py
Tried to improve type hinting for robot_skills/arm to make it more readable
=> (skills) Type hinting arm

robot_skills/src/robot_skills/arm/arms.py
This broke the robot interface with #1252. @P-ict0 @MatthijsBurgh please test your changes before merging
=> dont double convert timeout

hero_skills/src/hero_skills/hero.py, robot_skills/src/robot_skills/perception.py, robot_smach_states/examples/navigation/example_topological_navigation.py
This does break an example, but this is just not used right now
=> Disable not started parts

challenge_cleanup/src/challenge_cleanup/clean_inspect.py, challenge_cleanup/src/challenge_cleanup/self_cleanup.py, challenge_dishwasher/src/challenge_dishwasher/dishwasher.py, challenge_hand_me_that/src/challenge_hand_me_that/inspect_furniture_entity.py, challenge_restaurant/src/challenge_restaurant/restaurant.py, challenge_take_out_the_garbage/src/challenge_take_out_the_garbage/pick_up.py, robot_smach_states/benchmark/benchmark_grasping.py, robot_smach_states/examples/human_interaction/example_show_image.py, robot_smach_states/examples/world_model/example_get_show_map.py, robot_smach_states/src/robot_smach_states/clear.py, robot_smach_states/src/robot_smach_states/count_objects_on_location.py, robot_smach_states/src/robot_smach_states/human_interaction/find_people_in_room.py, robot_smach_states/src/robot_smach_states/human_interaction/show_image.py, robot_smach_states/src/robot_smach_states/manipulation/place.py, robot_smach_states/src/robot_smach_states/navigation/find.py, robot_smach_states/src/robot_smach_states/world_model/__init__.py, robot_smach_states/src/robot_smach_states/world_model/get_show_map.py, robot_smach_states/src/robot_smach_states/world_model/volumes.py, robot_smach_states/src/robot_smach_states/world_model/world_model.py, robot_smach_states/test/human_interaction/test_show_image.py, robot_smach_states/test/test_world_model.py
Best to review commits separately.
=> Add Show Map from final

challenge_spr/src/challenge_spr_states/detect.py, robot_skills/examples/example_person_recognition.py, robot_skills/src/robot_skills/perception.py, robot_smach_states/examples/human_interaction/example_detect_faces.py, robot_smach_states/src/robot_smach_states/human_interaction/detect_face.py, robot_smach_states/src/robot_smach_states/navigation/follow_operator.py, robot_smach_states/src/robot_smach_states/navigation/follow_operator2_0.py
As discussed in #1264.
The action server contains no calls to perception.detect_faces()
Fixes #1264
=> create consistent API for detect faces

robot_smach_states/src/robot_smach_states/human_interaction/entity_from_operator_pose.py
=> (smach_states) fix #1276

robot_smach_states/src/robot_smach_states/world_model/volumes.py
Removed "failed" from possible transitions
=> Fixed invalid transition

robot_smach_states/src/robot_smach_states/manipulation/place.py
Hero force drived backwards after it has placed an object
=> [place] Removed aggressive force drive after placing object

robot_smach_states/src/robot_smach_states/navigation/follow_operator.py
=> (follow operator) don't call ros Time now on construction.

challenge_carry_my_luggage/src/challenge_carry_my_luggage/carry_my_luggage.py
Optimized imports and removed old ones used in previous implementation
=> (Carry my luggage) Optimized imports

robot_smach_states/src/robot_smach_states/manipulation/place.py
Current implementation: Robot goes to the `prepare_place` pose BEFORE navigating to the place pose.
PR: Robot now doesn't move to the `prepare_place` pose anymore at any moment.
Also changed some asserts to use more correct type checking
=> (Place) Removed useless motion of arm and improved docs

robot_smach_states/src/robot_smach_states/manipulation/place.py
Removed unused variable and added type-hinting
=> (place.py) Typing and formatting

challenge_receptionist/src/challenge_receptionist/introduce_guest.py, challenge_receptionist/src/challenge_receptionist/receptionist.py, challenge_serve_breakfast/src/challenge_serve_breakfast/navigate_to_and_pick_item.py, robocup_knowledge/src/robocup_knowledge/environments/impuls/challenge_receptionist.py, robocup_knowledge/src/robocup_knowledge/environments/rwc2023/challenge_receptionist.py
This does work in simulation using Impuls
=> [rwc2023] receptionist

challenge_receptionist/src/challenge_receptionist/learn_guest.py, robot_smach_states/src/robot_smach_states/human_interaction/human_interaction.py, robot_smach_states/src/robot_smach_states/utility.py
Picovoice model updated to detect person names
=> Upgrade receptionist
