tue-robotics/tue_robocup

- robot_smach_states/src/robot_smach_states/startup.py
I need to disable the door option since I do not always want the robot
to start in front of the door.
> feature(): optional door argument to wait for door an drive in

- robot_skills/src/robot_skills/arms.py
- robot_skills/src/robot_skills/torso.py
- robot_smach_states/src/robot_smach_states/manipulation/grab.py
If timeouts exceeded in the wait_for_motion_done of the arms and
torso, all action goals are cancelled (if the parameter 'cancel'
is set to True)
> feature(Motion clients) Actions are cancelled if not reached in time

- robot_smach_states/src/robot_smach_states/util/startup.py
Allows to easily construct a robot by its name. 
Uses https://github.com/tue-robotics/tue_robocup/blob/master/robot_skills/src/robot_skills/util/robot_constructor.py
> Fix #210 to use robot_constructor of robot_skills. 

- robot_skills/src/robot_skills/world_model_ed.py
Now defaults to 0,0,0 in /<robot_name>/base_link, which makes more sense from the user's perspective (when do you ever want the closest room to (some point in) the /map frame?)
> fix(world_model_ed): get closest entity vector default

- robot_skills/src/robot_skills/api.py
Timeout bug is fixed. In general, I still think the class name Api is extremely confusing: this could be an API to anything, not just HMI.
Most important thing to fix this first though ;)
> fix(Api) Timeout is passed to HMI server

- robocup_knowledge/src/robocup_knowledge/environments/robotics_testlabs/common.py
This is apparently necessary for the hmi to work. Should actually be fixed in the hmi.
> fix(robotics_testlabs/common): names lower case for hmi to work

- robot_skills/src/robot_skills/util/robot_constructor.py
The argument is supplied in all use-cases according to ack-grep  --follow --python 'robot_constructor'
> Remove default robot name in robot_constructor

- robot_smach_states/package.xml
, which were compensated by in the install target
> Missing dependencies

- robot_skills/src/robot_skills/robot.py
Robot.py loads the parameters from the grasp offset from the robot description. I think this is a clean solution, since these values are robot-specific. This fixes issue #626. This PR goes together with PR 8 in sergio_description and 21 in amigo_description.
> changed hardcoded grasp_offset to be loaded from parameters

- robot_smach_states/env-hooks/60.robot_smach_states.sh.em
ipython is installed, because it is in the package.xml
depcheck was in amigo/sergio-user. These have already been removed.
> remove depcheck

- robot_skills/src/robot_skills/util/volume.py
The bottom_volume functions in volume.py have been renamed to bottom_area, which is what the emptyspotdesignator is searching for.
> Fixed conflicting names for emptyspotdesignator

- robot_smach_states/src/robot_smach_states/util/designators/arm.py
As per https://dev.azure.com/tue-robotics/tue-robotics/_build/results?buildId=408&view=logs&j=3588f332-17ad-5040-588c-7fa8695f6360&t=8a06a9b9-6f5b-50f7-18c3-72900e299def&l=315
The build error there is 
```
2019-10-01T22:52:52.7041098Z ************************
2019-10-01T22:52:52.7041208Z File "/home/amigo/ros/kinetic/system/src/robot_smach_states/src/robot_smach_states/util/designators/arm.py", line 59, in robot_smach_states.util.designators.arm.UnoccupiedArmDesignator
2019-10-01T22:52:52.7041307Z Failed example:
2019-10-01T22:52:52.7041377Z     assert arm_to_use_for_first_grab._arm in robot.arms
2019-10-01T22:52:52.7041433Z Exception raised:
2019-10-01T22:52:52.7041499Z     Traceback (most recent call last):
2019-10-01T22:52:52.7041561Z       File "/usr/lib/python2.7/doctest.py", line …
```
> Use Robot.arms as a dictionary, not as a list

- robot_smach_states/src/robot_smach_states/util/designators/core.py
Using a plain list makes created designators to exist forever. Using a weak reference to it allows it to be removed from memory, once nobody has a link to it.
As a result, the set will contain only the designators that are in use (or at least can be accessed).
Using a set means the order may get messed up, but a graph is built from the found designators, so the order doesn't seem highly relevant anyway.
> Use weak references to store active designators.

- robot_smach_states/examples/navigation/example_random_nav2.py
Initializing the base class of the base class looks wrong.
Fixing it in the normal way (ie only change `super(RandomNavDesignator, ...)` breaks, as `Designator does not allow being initialized without arguments.
Tracing its use in the same file:
```
173: self.random_nav_designator = RandomNavDesignator(self.robot)
221: states.NavigateToObserve(robot, self.random_nav_designator),
```
In `NavigateToObserve`:
```
17: def __init__(self, robot, entity_designator, radius=0.7, margin=0.075):
21: :param entity_designator: EdEntityDesignator for the object to observe
```
That class allows an empty contructor as well.
> Fix base class initialization of RandomNavDesignator

- robot_skills/src/robot_skills/perception.py
Now a subscriber is constructed again on request. This slows down the
executive state machine but makes sure that we do not flood the network.
> fix(robot_skills): Get rid of continuous image / depth subscriber

- challenge_help_me_carry/src/challenge_help_me_carry.py
- challenge_help_me_carry/src/challenge_help_me_carry2.py
- challenge_set_a_table/src/challenge_set_a_table_states/clear_manipulate_machine.py
- challenge_set_a_table/src/challenge_set_a_table_states/manipulate_machine.py
- challenge_storing_groceries/src/challenge_storing_groceries/manipulate_machine.py
- challenge_take_out_the_garbage/src/challenge_take_out_the_garbage/pick_up.py
- robot_smach_states/src/robot_smach_states/manipulation/place_designator.py
When merging our emptyspotdesignator we forgot to update some of the imports in challenges. Since the emptyspotdesignator is no longer with the other designators it cannot be imported as ds.Emptyspotdesignator
> fixed imports of Emptyspotdesignator

- robot_smach_states/src/robot_smach_states/util/designators/ed_designators.py
This is needed since we changed the way ed simple query service interprets radius=0 this used to mean that the position of the object didn't matter but now you need to specify that as radius=inf
> changed default radius to inf

- robot_skills/src/robot_skills/arms.py
- robot_skills/src/robot_skills/robot.py
Make it impossible to access the force sensor if the user din't ask for it, even if the hardware supports it.
> Enforce user request about accessing the force sensor

- robot_smach_states/src/robot_smach_states/util/designators/ed_designators.py
As suggested by @alberth in https://github.com/tue-robotics/tue_robocup/pull/1033/files#r424597213
> (designators) explicit return None in locking designator

- robot_skills/src/robot_skills/arm/arms.py
This thing got lost in the composable robot interface. I don't know how its possible that this bug never surfaced during any tests but it needs to be fixed. 
Without this parameter arm.send_goal **does not** work
> fix missing offset parameter

- challenge_presentation/src/challenge_presentation/presentation.py
- robot_skills/src/robot_skills/head.py
- robot_skills/src/robot_skills/mockbot.py
This function is not used in any challenges besides the presentation. Where it can easily be removed as it is only used to show that the camera can move around.
> remove look_at_hand function

- robot_smach_states/src/robot_smach_states/manipulation/grab.py
tf_listener was still used as keyword.
What is more concerning is that this was not caught by CI. A test should be added I think
> tf_listener keyword

- azure-pipelines.yml
The status checks only showed PR or push tests, because they had the same name. By changing the displayName, both show in the status checks. Which makes merging much safer, as I think often people forgot to check the other tests on azure.
> CI Improvement/fixes

- challenge_demo/scripts/demo.py
Task specification was a string with value "action_recipe"
Should be: action_recipe
Difficult to write down. It had ascii double quotes at the start and end of the string
> remove leading and trailing quotes

- robot_skills/src/robot_skills/arm/arms.py
This docstring has been outdated for a long time. timeout 0.0 has defined behaviour in that the function sends the command and returns quickly. Allowing a user to not wait for the result.
> (skills)(arm) timeout of 0.0 is allowed

- robot_smach_states/src/robot_smach_states/manipulation/grab.py
After various tests of grabbing objects from different surfaces we can safely remove the "lifting" part (`robot_smach_states/manipulation/grab.py`) after it grasped the object and go directly to "retract". Doesn't necessarily improve speed but simplifies the code.
Also added some type hinting.
> Cleanup of grab.py

- challenge_serve_breakfast/src/challenge_serve_breakfast/navigate_to_and_pick_item.py
Merge after #1326 
Fixes one of the issues in #1325
> Use handover detector to detect failed handover

- challenge_demo/scripts/demo.py
Some suggestions based on our demo today. Fixes the following problems:
1. reinstates wait for trigger. I find this useful for demos since the presenter can determine the tempo of the presentation. Otherwise the robot is constantly asking for validation. 
2. Fix the timeout logic for not hearing the operator. Previous implementation just continued with the loop which crashes if the sentence parameter was not initialised. Otherwise it will just redo the previous command. Now it says "oops we couldn't do it." and waits for the next trigger.
> Demo peter
